version: 2

# Tell RTD which build image to use and which Python to install
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Explicitly set the version of Python and its requirements
python:
  install:
    - requirements: docs/requirements.txt
    - requirements: requirements.txt